version: "3.9"

services:
  # nestjs:
  #   build: .
  #   container_name: ${DOCKER_PROJECT_NAME}_nestjs_app
  #   ports:
  #     - "127.0.0.1:${PORT}:3002"
  #   volumes:
  #     - .:/usr/src/app   # source kodni container bilan sinxronizatsiya
  #     # - /usr/src/app/node_modules   # bu qatorni olib tashladik
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_NAME=${DOCKER_PROJECT_NAME}
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #   depends_on:
  #     - postgres
  #   command: npm run start:dev

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: ${DOCKER_PROJECT_NAME}_postgres
    ports:
      - "127.0.0.1:${DOCKER_DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DOCKER_PROJECT_NAME}

volumes:
  postgres_data:
